#!/usr/bin/env bash
# Generate a DuoFold release keystore OUTSIDE the repository.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
JAVA_HOME="${JAVA_HOME:-}"
if [[ -z "${JAVA_HOME}" && -x "$ROOT/.jdk/jdk-17.0.13+11/bin/keytool" ]]; then
  JAVA_HOME="$ROOT/.jdk/jdk-17.0.13+11"
fi
KEYTOOL="${JAVA_HOME:+$JAVA_HOME/bin/}keytool"
command -v "$KEYTOOL" >/dev/null 2>&1 || KEYTOOL=keytool

DIR="${DUOFOLD_KEYSTORE_DIR:-$HOME/.local/share/duofold}"
STORE="$DIR/duofold-release.jks"
ENV_FILE="$DIR/keystore.env"
ALIAS="${DUOFOLD_RELEASE_KEY_ALIAS:-duofold}"

mkdir -p "$DIR"
chmod 700 "$DIR"

if [[ -f "$STORE" ]]; then
  echo "Keystore already exists: $STORE"
  echo "Refusing to overwrite. Delete it manually if you intend to rotate keys."
  exit 1
fi

# Random passwords; stored only in keystore.env (mode 600).
STORE_PASS="$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"
KEY_PASS="$STORE_PASS"

"$KEYTOOL" -genkeypair \
  -keystore "$STORE" \
  -storetype JKS \
  -alias "$ALIAS" \
  -keyalg RSA \
  -keysize 2048 \
  -validity 10000 \
  -storepass "$STORE_PASS" \
  -keypass "$KEY_PASS" \
  -dname "CN=DuoFold Release, OU=DuoFold, O=DuoFold, L=Unknown, ST=Unknown, C=CN"

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/generate-release-keystore.sh — do not commit
export DUOFOLD_RELEASE_STORE_FILE="$STORE"
export DUOFOLD_RELEASE_STORE_PASSWORD="$STORE_PASS"
export DUOFOLD_RELEASE_KEY_ALIAS="$ALIAS"
export DUOFOLD_RELEASE_KEY_PASSWORD="$KEY_PASS"
EOF
chmod 600 "$ENV_FILE" "$STORE"

echo "Created:"
echo "  $STORE"
echo "  $ENV_FILE"
echo "Build with: ./scripts/release-signed.sh"
